name: 📩 CloudPos 개선/요청
description: 화면 수정, 설정 변경, 문서 요청 등 CloudPosProject 개선사항을 남길 때 사용하세요.
title: "[REQ] "
labels: ["request"]
body:
  - type: input
    id: title
    attributes:
      label: 요청 제목
      placeholder: 예) 포스기-점주 매핑 화면에 검색 추가
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 배경/상황
      description: 어떤 업무를 하다가 필요했는지 적어주세요.
  - type: textarea
    id: what
    attributes:
      label: 요청 내용
      placeholder: 예) 점주명/포스기ID로 필터링할 수 있게 해주세요.
      validations:
        required: true
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - 낮음
        - 보통
        - 높음
