name: 🐛 CloudPos 버그 신고
description: CloudPosProject에서 실제 동작이 기대와 다를 때 사용하세요.
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: 버그 요약
      placeholder: 예) 결제 완료 후 장바구니가 비워지지 않음
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 재현 절차
      description: 어떤 순서로 했을 때 발생했는지 적어주세요.
      placeholder: |
        1. 상품 A 장바구니 추가
        2. 카드 결제 진행
        3. 결제 완료 콜백 수신
        4. 장바구니 여전히 존재
  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
      placeholder: 예) 결제 성공 시 해당 장바구니는 삭제되어야 함
  - type: textarea
    id: env
    attributes:
      label: 환경
      placeholder: 예) dev 서버 / Chrome 129 / 2025-10-30
  
  
